### PR TITLE
step_port_forward: add access to localhost if necessary

### LINKED ISSUE #104: HTTP server is unreachable by default in recent Virtualbox versions
#### Overview of the Issue

Starting from Virtualbox 7.0.0, packer http server is not reachable from the guests by default.

This is due to a new security option `--nat-localhostreachableN` (introduced in Virtualbox 7.0.0) which is "off" by default, disabling access to host gateway (10.0.2.2) directly. This is not apparent in changelogs as this is a security change, which Oracle does not communicate transparently.

Thanks klaus-vb from #vbox:irc.oftc.net for this info!

#### Proposed fix

Configure virtualbox vm with `--nat-localhostreachable1 on` on Virtualbox versions >= 7.0.0 (<7.0.0 do not have this option).

Until then, this is the workaround:

```hcl
vboxmanage = [
  ["modifyvm", "{{.Name}}", "--nat-localhostreachable1", "on"],
]
```

#### Reproduction Steps

See https://github.com/hashicorp/packer/issues/12118

### PR DESCRIPTION
**Pull request by pdietl**
Closes #104

For Virtualbox versions >= 7.0, access to the host's network (via 10.0.2.2) is blocked by default unless the
`--nat-localhostreachableN=on` option is used.

### CODE REVIEW

**Comment by pdietl** [comment]
@nywilken could you take a look at this?

**Review by lbajolet-hashicorp — CHANGES_REQUESTED** [review]
Hi @pdietl, 

Sorry about the time it took for us to take a look, that one flew under our radar, apologies for that.

I left a couple of comments on the code, I think it'd be clearer if the `addAccessToLocalhost` function returned an error instead of an action, then the caller can decide what to do with that error. There's also the semver creation from the constant, I believe this would be best to execute as part of the [`init`](https://golang.org/doc/effective_go.html#init) function, which is automatically invoked when the binary is executed. This would make it more robust as if for any reason the code doesn't work later on, we'll catch it proactively instead of when the step executes with the right version of virtualbox installed.

Aside from that, this looks good to me, please feel free to ping again when you've had time to address this feedback, and I'll take a second look then.

Thanks!

**Comment by pdietl** [comment]
@lbajolet-hashicorp I believe I addressed all of your comments.

**Comment by pdietl** [comment]
@lbajolet-hashicorp I can also add unit tests if you'd like.

**Review by lbajolet-hashicorp — COMMENTED** [review]
Hi @pdietl,

Thank you for the reroll! In the current state the code looks good to me, I just left a last comment on the version being read, and there's some lint/compile errors in the step you added, when you address those I believe we'll be ready to merge this PR.

**Comment by lbajolet-hashicorp** [comment]
> @lbajolet-hashicorp I can also add unit tests if you'd like.

If you have time for them, this would definitely be appreciated, thanks!

**Comment by pdietl** [comment]
@lbajolet-hashicorp I added unit tests, formatted, and fixed compilation errors.
Here is some output of it working locally for me:
```
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 VBoxManage --version output: 7.0.15r161716
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 VirtualBox version: 7.0.15
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 Executing VBoxManage: []string{"modifyvm", "packer-virtualbox-1709170875", "--nat-localhostreachable1", "on"}
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 stdout:
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 stderr:
2024/02/28 17:41:17 packer-plugin-virtualbox plugin: 2024/02/28 17:41:17 [TRACE] VirtualBox's version ("v7.0.15") is >= "v7.0.0", setting --nat-localhostreachable1 on
```

**Comment by pdietl** [comment]
Also, I would appreciate it if you could release a new version after accepting this. :)

File: builder/virtualbox/common/step_port_forwarding.go [hunk 1]
```diff
@@ -34,6 +36,58 @@ type StepPortForwarding struct {
...
+	const vboxVerMinNeedLHReachableNonCanon = "v7.0"
+	var err error
+	vboxVerMinNeedLHReachable, err = getCanonicalSemver(vboxVerMinNeedLHReachableNonCanon)
+	if err != nil {
+		fmt.Fprintf(os.Stderr, "Plugin failure: %v\nPlease open a Github issue for this plugin.\n", err)
+		os.Exit(1)
+	}
+}
+
+func getCanonicalSemver(version_string string) (string, error) {
```
Comment (lbajolet-hashicorp) [inline builder/virtualbox/common/step_port_forwarding.go:51]: Generally in Go it's preferred to use camelCase rather than snake_case for local/private entities.

File: builder/virtualbox/common/step_port_forwarding_test.go [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+import (
+	"reflect"
+	"testing"
+)
+
+const validSemver = "v7.0"
+const invalidSemver = "v7.0.0abcd"
+
+func TestValidSemver(t *testing.T) {
```
Comment (lbajolet-hashicorp) [inline builder/virtualbox/common/step_port_forwarding_test.go:14]: I'm not sure it's relevant to add this test since the code that does the conversion comes from another package, so as long as the dependency does the canonicalisation correctly, we shouldn't have any problem.

File: builder/virtualbox/common/step_port_forwarding.go [hunk 3]
```diff
@@ -34,6 +36,58 @@ type StepPortForwarding struct {
...
+	canonical_semver := semver.Canonical(version_string)
+	if canonical_semver == "" {
+		return "", fmt.Errorf("String '%s' is not a valid semver", version_string)
```
Comment (lbajolet-hashicorp) [inline builder/virtualbox/common/step_port_forwarding.go:54]: Instead of `'%s'` for quoted strings, you can use `%q` for this purpose

```suggestion
		return "", fmt.Errorf("String %q is not a valid semver", version_string)
```

**Review by lbajolet-hashicorp — COMMENTED** [review]
Hi @pdietl,

We're getting there, I'm not sure we should unit-test the semver library, but aside from that this looks good to me.

I'll update the code to simplify this, and merge if it goes green directly after that.
Releasing the plugin after sounds good to me; I'll try to get it done today, or tomorrow at worst.

Thanks!

**Review by lbajolet-hashicorp — APPROVED** [review]
